#!/bin/bash

echo "======================================================"
echo "🏄 DEPLOY DO CONTRATO SURFISTANFT"
echo "======================================================"
echo ""
echo "📋 PREPARAÇÃO PARA DEPLOY:"
echo ""
echo "1. Configure a variável de ambiente FLOW_PRIVATE_KEY:"
echo "   export FLOW_PRIVATE_KEY='sua_chave_privada_aqui'"
echo ""
echo "2. O contrato será deployado em:"
echo "   Rede: Testnet"
echo "   Conta: 0x36395f9dde50ea27"
echo ""
echo "3. Recursos do contrato SurfistaNFT:"
echo "   ✅ NFT única para cada surfista"
echo "   ✅ Sistema de numeração automática (Diego, Diego#2, etc)"
echo "   ✅ Bag de conhecimento permanente"
echo "   ✅ Vault de FLOW para recompensas"
echo "   ✅ Sistema de conquistas"
echo "   ✅ Rastreamento de profundidade"
echo ""
echo "4. Comando para deploy (após configurar a chave):"
echo "   flow project deploy --network testnet"
echo ""
echo "======================================================"
echo "📄 CONTRATO ATUALIZADO COM:"
echo "======================================================"
echo ""
echo "🆕 Sistema de Numeração de Nomes:"
echo "   - Registro global de nomes (nomeRegistry)"
echo "   - Auto-incremento quando nome já existe"
echo "   - Ex: Diego, Diego#2, Diego#3..."
echo ""
echo "📚 Bag de Conhecimento:"
echo "   - Comandos: +5 pontos"
echo "   - Arquivos: +10 pontos"
echo "   - Funcionalidades: +15 pontos"
echo "   - Tesouros: +25 pontos"
echo "   - Conquistas: +50 pontos"
echo ""
echo "🏆 Conquistas Desbloqueáveis:"
echo "   - Wave Rider (tutorial completo)"
echo "   - Deep Diver (5 pastas exploradas)"
echo "   - Flow Master (NFT criada)"
echo "   - Treasure Hunter (100 pontos)"
echo "   - Rescue Complete (superfície alcançada)"
echo ""
echo "======================================================"
echo "🚀 APÓS O DEPLOY:"
echo "======================================================"
echo ""
echo "Use os scripts para interagir:"
echo "1. resgatar_surfista.cdc - Mintar NFT para surfista"
echo "2. adicionar_conhecimento.cdc - Add itens à bag"
echo "3. ver_surfista_status.cdc - Ver status completo"
echo ""
echo "Exemplo de uso:"
echo "flow transactions send ./scripts/resgatar_surfista.cdc 'Diego' --network testnet --signer bootcamp-account"
echo ""
echo "======================================================"